# Generated by Django 4.0.6 on 2022-07-27 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField()),
                ('model', models.BooleanField()),
                ('lr', models.FloatField()),
                ('optimizer', models.BooleanField()),
                ('epoch', models.IntegerField()),
                ('batch_size', models.IntegerField()),
                ('author', models.TextField()),
                ('log', models.TextField()),
                ('state', models.BooleanField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_date', models.DateTimeField()),
                ('acc', models.FloatField()),
                ('device', models.TextField()),
            ],
        ),
    ]
